In [2]:
from numpy import load

data = load('../data/hr_data.npz')
lst = data.files
for item in lst:
    print(f"{item} first 10:")
    print(data[item][:10])
    print(f"{item} last 10:")
    print(data[item][-10:])
    print()

t first 10:
[0 1 2 3 4 5 6 7 8 9]
t last 10:
[403190 403191 403192 403193 403194 403195 403196 403197 403198 403199]

state first 10:
[0 0 0 0 0 0 0 0 0 0]
state last 10:
[1 1 1 1 1 1 1 1 1 1]

hr first 10:
[60.26448679 60.1397942  57.81214478 58.19699544 58.73428726 58.60810667
 58.47633456 59.1918098  59.17016531 60.17623608]
hr last 10:
[92.87177876 89.00177415 89.95171285 88.45260797 85.58199079 86.32942928
 86.07485595 88.17416976 92.47014485 91.41018335]

